apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
espresso:
  app: ./app/build/outputs/apk/debug/app-debug.apk
  testApp: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
suites:
  - name: Evinced Espresso Tests
    emulators:
      - name: "Android GoogleAPI Emulator"
        platformVersions:
          - "15.0"
