apiVersion: v1alpha
kind: espresso
sauce:
  region: us-west-1
espresso:
  app: ./app/build/outputs/apk/debug/app-debug.apk
  testApp: ./app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
  otherApps:
    - storage:filename=com.evinced.demoapp-MK.apk
suites:
  - name: Evinced Espresso Tests
    testOptions:
      instrumentationArgs:
        EVINCED_SERVICE_ID: $EVINCED_SERVICE_ID
        EVINCED_API_KEY: $EVINCED_API_KEY
    devices:
      - name: "Google Pixel.*"
        platformVersion: "14"
        options:
          deviceType: PHONE
